### PR TITLE
Fix variable detection problem

### LINKED ISSUE #2: Detect variable names of body structures
Detect the current name and type of structures that are expected.

the actual example/state is:
"{
   "string":"string"
}"

it should be:
"{
   "name":"string"
}"

### PR DESCRIPTION
**Pull request by Pbarroca**
This closes #2
This fix should detect body objects and their types.
It also supports children objects, recursively.

### CODE REVIEW

File: router_processor.go [hunk 1]
```diff
@@ -131,30 +162,59 @@ func (rp *RouteParser) searchForStruct(name string, paths []string) (result []st
...
-					result = append(result, typeResult[1])
 				}
 			} else if strings.HasPrefix(lineText, comp) {
 				isFound = true
 			}
 		}
 		file.Close()
 	}
+
+	//this means it doesn't found the struct in the candidated files. We should search the packages again!
```
Comment (ambernardino) [inline router_processor.go]: this means it didn't find

**Review by ambernardino — APPROVED** [review]
